#?filename=deploy-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwekkerclient
spec:
  selector:
    matchLabels:
      app: kwekkerclient
  replicas: 1
  template:
    metadata:
      labels:
        app: kwekkerclient
    spec:
      containers:
        - name: kwekkerclient
          image: stefv013/kwekkerclient
          imagePullPolicy: Always
          ports:
            - name: listen-port
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 512Mi